# Generated by 'click-buildtool elem2make' on 2020年 02月 29日 星期六 02:06:04 CST
ELEMENT_OBJS__0 = \
gatewaySender.u.o \
middleboxFW.u.o \
middleboxIDS.u.o \
middleboxLB.u.o \
veritools.u.o \

ELEMENT_OBJS = \
$(ELEMENT_OBJS__0) \

$(ELEMENT_OBJS__0): %.u.o: ./%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
	$(FIXDEP)
$(patsubst %.u.o,%.s,$(ELEMENT_OBJS__0)): %.s: ./%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)
$(patsubst %.u.o,%.ii,$(ELEMENT_OBJS__0)): %.ii: ./%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)

ELEMENT_LIBS = -lverimb -lcryptopp
